### ISSUE TITLE
Client::PAGINATION_PREVIOUS

### ISSUE THREAD

**Issue by kris10ansn** [pimssas/pims-api-client-php#48]
Client::PAGINATION_PREVIOUS is set to 'previous'. `$response->hasLink(Client::PAGINATION_PREVIOUS)` will always return false, I believe you have to use `$response->hasLink('prev');`. Shouldn't the constant be 'prev' here?

**Comment by TantePata** [comment]
Fix by https://github.com/pimssas/pims-api-client-php/pull/49
